package org.eightofour.moneytransfer.web.rest.model.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * View class for error response
 * generated by business exception throwing.
 *
 * @author Evgeny Zubenko
 */
@Getter
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
public class ErrorResponse {
    /**
     * HTTP code.
     */
    @JsonProperty
    private int code;

    /**
     * Error message.
     */
    @JsonProperty
    private String message;
}