package org.eightofour.moneytransfer.web.rest.model.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;

/**
 * View class for error response
 * generated by business exception throwing.
 *
 * @author Evgeny Zubenko
 */
@AllArgsConstructor
public class ErrorResponse {
    /**
     * HTTP code.
     */
    @JsonProperty
    private int code;

    /**
     * Error message.
     */
    @JsonProperty
    private String message;
}